//
//  MunicipioViewModel.swift
//  ListaFuncionariosApp
//
//  Created by Matheus Braschi Haliski on 19/09/25.
//

internal import CoreData
import Combine

@MainActor 
class MunicipioViewModel: ObservableObject {
    
    @Published var municipios: [Municipio] = []
    private var viewContext: NSManagedObjectContext
    
    init(context: NSManagedObjectContext) {
        self.viewContext = context
        fetchMunicipios()
    }
    
    func fetchMunicipios() {
        let request: NSFetchRequest<Municipio> = Municipio.fetchRequest()
        request.sortDescriptors = [
            NSSortDescriptor(keyPath: \Municipio.nome, ascending: true),
            NSSortDescriptor(keyPath: \Municipio.regional, ascending: true)
        ]
        do {
            municipios = try viewContext.fetch(request)
        } catch {
            print("Erro ao buscar municípios: \(error)")
        }
    }
    
    func popularMunicipiosSeNecessario() {
        let countRequest: NSFetchRequest<Municipio> = Municipio.fetchRequest()
        countRequest.includesSubentities = false
        countRequest.fetchLimit = 1
        if let count = try? viewContext.count(for: countRequest), count > 0 { return }
        
        do {
            let mapaRegionais: [String: String] = [
                "ALTAMIRA DO PARANA": "CAMPO MOURÃO",
                "ARARUNA": "CAMPO MOURÃO",
                "BARBOSA FERRAZ": "CAMPO MOURÃO",
                "BOA ESPERANCA": "CAMPO MOURÃO",
                "CAMPINA DA LAGOA": "CAMPO MOURÃO",
                "CAMPO MOURAO": "CAMPO MOURÃO",
                "CORUMBATAI DO SUL": "CAMPO MOURÃO",
                "ENGENHEIRO BELTRAO": "CAMPO MOURÃO",
                "FAROL": "CAMPO MOURÃO",
                "FENIX": "CAMPO MOURÃO",
                "GOIOERE": "CAMPO MOURÃO",
                "IRETAMA": "CAMPO MOURÃO",
                "JANIOPOLIS": "CAMPO MOURÃO",
                "JURANDA": "CAMPO MOURÃO",
                "LUIZIANA": "CAMPO MOURÃO",
                "MAMBORE": "CAMPO MOURÃO",
                "MOREIRA SALES": "CAMPO MOURÃO",
                "NOVA CANTU": "CAMPO MOURÃO",
                "NOVA TEBAS": "CAMPO MOURÃO",
                "PEABIRU": "CAMPO MOURÃO",
                "QUARTO CENTENARIO": "CAMPO MOURÃO",
                "QUINTA DO SOL": "CAMPO MOURÃO",
                "RANCHO ALEGRE DO OESTE": "CAMPO MOURÃO",
                "RONCADOR": "CAMPO MOURÃO",
                "TERRA BOA": "CAMPO MOURÃO",
                "TUNEIRAS DO OESTE": "CAMPO MOURÃO",
                "UBIRATA": "CAMPO MOURÃO",
                "ANAHY": "CASCAVEL",
                "ASSIS CHATEAUBRIAND": "CASCAVEL",
                "BOA VISTA DA APARECIDA": "CASCAVEL",
                "BRAGANEY": "CASCAVEL",
                "CAFELANDIA": "CASCAVEL",
                "CAMPO BONITO": "CASCAVEL",
                "CAPITAO LEONIDAS MARQUES": "CASCAVEL",
                "CASCAVEL": "CASCAVEL",
                "CATANDUVAS": "CASCAVEL",
                "CEU AZUL": "CASCAVEL",
                "CORBELIA": "CASCAVEL",
                "DIAMANTE DO OESTE": "CASCAVEL",
                "DIAMANTE DO SUL": "CASCAVEL",
                "ENTRE RIOS DO OESTE": "CASCAVEL",
                "ESPIGAO ALTO DO IGUACU": "CASCAVEL",
                "FORMOSA DO OESTE": "CASCAVEL",
                "FOZ DO IGUACU": "CASCAVEL",
                "GUAIRA": "CASCAVEL",
                "GUARANIACU": "CASCAVEL",
                "IBEMA": "CASCAVEL",
                "IGUATU": "CASCAVEL",
                "IRACEMA DO OESTE": "CASCAVEL",
                "ITAIPULANDIA": "CASCAVEL",
                "JESUITAS": "CASCAVEL",
                "LINDOESTE": "CASCAVEL",
                "MARECHAL CANDIDO RONDON": "CASCAVEL",
                "MARIPA": "CASCAVEL",
                "MATELANDIA": "CASCAVEL",
                "MEDIANEIRA": "CASCAVEL",
                "MERCEDES": "CASCAVEL",
                "MISSAL": "CASCAVEL",
                "NOVA AURORA": "CASCAVEL",
                "NOVA SANTA ROSA": "CASCAVEL",
                "OURO VERDE DO OESTE": "CASCAVEL",
                "PALOTINA": "CASCAVEL",
                "PATO BRAGADO": "CASCAVEL",
                "QUATRO PONTES": "CASCAVEL",
                "QUEDAS DO IGUACU": "CASCAVEL",
                "RAMILANDIA": "CASCAVEL",
                "SANTA HELENA": "CASCAVEL",
                "SANTA LUCIA": "CASCAVEL",
                "SANTA TEREZA DO OESTE": "CASCAVEL",
                "SANTA TEREZINHA DE ITAIPU": "CASCAVEL",
                "SAO JOSE DAS PALMEIRAS": "CASCAVEL",
                "SAO MIGUEL DO IGUACU": "CASCAVEL",
                "SAO PEDRO DO IGUACU": "CASCAVEL",
                "SERRANOPOLIS DO IGUACU": "CASCAVEL",
                "TERRA ROXA": "CASCAVEL",
                "TOLEDO": "CASCAVEL",
                "TRES BARRAS DO PARANA": "CASCAVEL",
                "TUPASSI": "CASCAVEL",
                "VERA CRUZ DO OESTE": "CASCAVEL",
                "ADRIANOPOLIS": "CURITIBA",
                "AGUDOS DO SUL": "CURITIBA",
                "ALMIRANTE TAMANDARE": "CURITIBA",
                "ANTONINA": "CURITIBA",
                "ARAUCARIA": "CURITIBA",
                "BALSA NOVA": "CURITIBA",
                "BOCAIUVA DO SUL": "CURITIBA",
                "CAMPINA GRANDE DO SUL": "CURITIBA",
                "CAMPO DO TENENTE": "CURITIBA",
                "CAMPO LARGO": "CURITIBA",
                "CAMPO MAGRO": "CURITIBA",
                "CERRO AZUL": "CURITIBA",
                "COLOMBO": "CURITIBA",
                "CONTENDA": "CURITIBA",
                "CURITIBA": "CURITIBA",
                "DOUTOR ULYSSES": "CURITIBA",
                "FAZENDA RIO GRANDE": "CURITIBA",
                "GUARAQUECABA": "CURITIBA",
                "GUARATUBA": "CURITIBA",
                "ITAPERUCU": "CURITIBA",
                "LAPA": "CURITIBA",
                "MANDIRITUBA": "CURITIBA",
                "MATINHOS": "CURITIBA",
                "MORRETES": "CURITIBA",
                "PARANAGUA": "CURITIBA",
                "PIEN": "CURITIBA",
                "PINHAIS": "CURITIBA",
                "PIRAQUARA": "CURITIBA",
                "PONTAL DO PARANA": "CURITIBA",
                "QUATRO BARRAS": "CURITIBA",
                "QUITANDINHA": "CURITIBA",
                "RIO BRANCO DO SUL": "CURITIBA",
                "RIO NEGRO": "CURITIBA",
                "SAO JOSE DOS PINHAIS": "CURITIBA",
                "TIJUCAS DO SUL": "CURITIBA",
                "TUNAS DO PARANA": "CURITIBA",
                "BOA VENTURA DE SAO ROQUE": "GUARAPUAVA",
                "CAMPINA DO SIMAO": "GUARAPUAVA",
                "CANDOI": "GUARAPUAVA",
                "CANTAGALO": "GUARAPUAVA",
                "FOZ DO JORDAO": "GUARAPUAVA",
                "GOIOXIM": "GUARAPUAVA",
                "GUARAPUAVA": "GUARAPUAVA",
                "LARANJAL": "GUARAPUAVA",
                "LARANJEIRAS DO SUL": "GUARAPUAVA",
                "MARQUINHO": "GUARAPUAVA",
                "MATO RICO": "GUARAPUAVA",
                "NOVA LARANJEIRAS": "GUARAPUAVA",
                "PALMITAL": "GUARAPUAVA",
                "PINHAO": "GUARAPUAVA",
                "PITANGA": "GUARAPUAVA",
                "PORTO BARREIRO": "GUARAPUAVA",
                "PRUDENTOPOLIS": "GUARAPUAVA",
                "RESERVA DO IGUACU": "GUARAPUAVA",
                "RIO BONITO DO IGUACU": "GUARAPUAVA",
                "SANTA MARIA DO OESTE": "GUARAPUAVA",
                "TURVO": "GUARAPUAVA",
                "VIRMOND": "GUARAPUAVA",
                "ALVORADA DO SUL": "LONDRINA",
                "APUCARANA": "LONDRINA",
                "ARAPONGAS": "LONDRINA",
                "ARAPUA": "LONDRINA",
                "ARIRANHA DO IVAI": "LONDRINA",
                "ASSAI": "LONDRINA",
                "BELA VISTA DO PARAISO": "LONDRINA",
                "BOM SUCESSO": "LONDRINA",
                "BORRAZOPOLIS": "LONDRINA",
                "CALIFORNIA": "LONDRINA",
                "CAMBE": "LONDRINA",
                "CAMBIRA": "LONDRINA",
                "CENTENARIO DO SUL": "LONDRINA",
                "CORNELIO PROCOPIO": "LONDRINA",
                "CRUZMALTINA": "LONDRINA",
                "FAXINAL": "LONDRINA",
                "FLORESTOPOLIS": "LONDRINA",
                "GODOY MOREIRA": "LONDRINA",
                "GRANDES RIOS": "LONDRINA",
                "IBIPORA": "LONDRINA",
                "IVAIPORA": "LONDRINA",
                "JAGUAPITA": "LONDRINA",
                "JANDAIA DO SUL": "LONDRINA",
                "JARDIM ALEGRE": "LONDRINA",
                "JATAIZINHO": "LONDRINA",
                "KALORE": "LONDRINA",
                "LEOPOLIS": "LONDRINA",
                "LIDIANOPOLIS": "LONDRINA",
                "LONDRINA": "LONDRINA",
                "LUNARDELLI": "LONDRINA",
                "MANOEL RIBAS": "LONDRINA",
                "MARILANDIA DO SUL": "LONDRINA",
                "MARUMBI": "LONDRINA",
                "MAUA DA SERRA": "LONDRINA",
                "MIRASELVA": "LONDRINA",
                "NOVA AMERICA DA COLINA": "LONDRINA",
                "NOVA SANTA BARBARA": "LONDRINA",
                "NOVO ITACOLOMI": "LONDRINA",
                "PITANGUEIRAS": "LONDRINA",
                "PORECATU": "LONDRINA",
                "PRADO FERREIRA": "LONDRINA",
                "PRIMEIRO DE MAIO": "LONDRINA",
                "RANCHO ALEGRE": "LONDRINA",
                "RIO BOM": "LONDRINA",
                "RIO BRANCO DO IVAI": "LONDRINA",
                "ROLANDIA": "LONDRINA",
                "ROSARIO DO IVAI": "LONDRINA",
                "SABAUDIA": "LONDRINA",
                "SANTA CECILIA DO PAVAO": "LONDRINA",
                "SANTO ANTONIO DO PARAISO": "LONDRINA",
                "SAO JERONIMO DA SERRA": "LONDRINA",
                "SAO JOAO DO IVAI": "LONDRINA",
                "SAO PEDRO DO IVAI": "LONDRINA",
                "SAO SEBASTIAO DA AMOREIRA": "LONDRINA",
                "SAPOPEMA": "LONDRINA",
                "SERTANEJA": "LONDRINA",
                "SERTANOPOLIS": "LONDRINA",
                "TAMARANA": "LONDRINA",
                "URAI": "LONDRINA",
                "ALTO PARANA": "MARINGÁ",
                "AMAPORA": "MARINGÁ",
                "ANGULO": "MARINGÁ",
                "ASTORGA": "MARINGÁ",
                "ATALAIA": "MARINGÁ",
                "CAFEARA": "MARINGÁ",
                "CIANORTE": "MARINGÁ",
                "COLORADO": "MARINGÁ",
                "CRUZEIRO DO SUL": "MARINGÁ",
                "DIAMANTE DO NORTE": "MARINGÁ",
                "DOUTOR CAMARGO": "MARINGÁ",
                "FLORAI": "MARINGÁ",
                "FLORESTA": "MARINGÁ",
                "FLORIDA": "MARINGÁ",
                "GUAIRACA": "MARINGÁ",
                "GUAPOREMA": "MARINGÁ",
                "GUARACI": "MARINGÁ",
                "IGUARACU": "MARINGÁ",
                "INAJA": "MARINGÁ",
                "INDIANOPOLIS": "MARINGÁ",
                "ITAGUAJE": "MARINGÁ",
                "ITAMBE": "MARINGÁ",
                "ITAUNA DO SUL": "MARINGÁ",
                "IVATUBA": "MARINGÁ",
                "JAPURA": "MARINGÁ",
                "JARDIM OLINDA": "MARINGÁ",
                "JUSSARA": "MARINGÁ",
                "LOANDA": "MARINGÁ",
                "LOBATO": "MARINGÁ",
                "LUPIONOPOLIS": "MARINGÁ",
                "MANDAGUACU": "MARINGÁ",
                "MANDAGUARI": "MARINGÁ",
                "MARIALVA": "MARINGÁ",
                "MARILENA": "MARINGÁ",
                "MARINGA": "MARINGÁ",
                "MIRADOR": "MARINGÁ",
                "MUNHOZ DE MELLO": "MARINGÁ",
                "NOSSA SENHORA DAS GRACAS": "MARINGÁ",
                "NOVA ALIANCA DO IVAI": "MARINGÁ",
                "NOVA ESPERANCA": "MARINGÁ",
                "NOVA LONDRINA": "MARINGÁ",
                "OURIZONA": "MARINGÁ",
                "PAICANDU": "MARINGÁ",
                "PARAISO DO NORTE": "MARINGÁ",
                "PARANACITY": "MARINGÁ",
                "PARANAPOEMA": "MARINGÁ",
                "PARANAVAI": "MARINGÁ",
                "PLANALTINA DO PARANA": "MARINGÁ",
                "PORTO RICO": "MARINGÁ",
                "PRESIDENTE CASTELO BRANCO": "MARINGÁ",
                "RONDON": "MARINGÁ",
                "SANTA CRUZ DO MONTE CASTELO": "MARINGÁ",
                "SANTA FE": "MARINGÁ",
                "SANTA INES": "MARINGÁ",
                "SANTA ISABEL DO IVAI": "MARINGÁ",
                "SANTO ANTONIO DO CAIUA": "MARINGÁ",
                "SANTO INACIO": "MARINGÁ",
                "SAO CARLOS DO IVAI": "MARINGÁ",
                "SAO JOAO DO CAIUA": "MARINGÁ",
                "SAO JORGE DO IVAI": "MARINGÁ",
                "SAO MANOEL DO PARANA": "MARINGÁ",
                "SAO PEDRO DO PARANA": "MARINGÁ",
                "SAO TOME": "MARINGÁ",
                "SARANDI": "MARINGÁ",
                "TAMBOARA": "MARINGÁ",
                "TERRA RICA": "MARINGÁ",
                "UNIFLOR": "MARINGÁ",
                "AMPERE": "PATO BRANCO",
                "BARRACAO": "PATO BRANCO",
                "BELA VISTA DA CAROBA": "PATO BRANCO",
                "BOA ESPERANCA DO IGUACU": "PATO BRANCO",
                "BOM JESUS DO SUL": "PATO BRANCO",
                "BOM SUCESSO DO SUL": "PATO BRANCO",
                "CAPANEMA": "PATO BRANCO",
                "CHOPINZINHO": "PATO BRANCO",
                "CLEVELANDIA": "PATO BRANCO",
                "CORONEL DOMINGOS SOARES": "PATO BRANCO",
                "CORONEL VIVIDA": "PATO BRANCO",
                "CRUZEIRO DO IGUACU": "PATO BRANCO",
                "DOIS VIZINHOS": "PATO BRANCO",
                "ENEAS MARQUES": "PATO BRANCO",
                "FLOR DA SERRA DO SUL": "PATO BRANCO",
                "FRANCISCO BELTRAO": "PATO BRANCO",
                "HONORIO SERPA": "PATO BRANCO",
                "ITAPEJARA DO OESTE": "PATO BRANCO",
                "MANFRINOPOLIS": "PATO BRANCO",
                "MANGUEIRINHA": "PATO BRANCO",
                "MARIOPOLIS": "PATO BRANCO",
                "MARMELEIRO": "PATO BRANCO",
                "NOVA ESPERANCA DO SUDOESTE": "PATO BRANCO",
                "NOVA PRATA DO IGUACU": "PATO BRANCO",
                "PALMAS": "PATO BRANCO",
                "PATO BRANCO": "PATO BRANCO",
                "PEROLA DO OESTE": "PATO BRANCO",
                "PINHAL DE SAO BENTO": "PATO BRANCO",
                "PLANALTO": "PATO BRANCO",
                "PRANCHITA": "PATO BRANCO",
                "REALEZA": "PATO BRANCO",
                "RENASCENCA": "PATO BRANCO",
                "SALGADO FILHO": "PATO BRANCO",
                "SALTO DO LONTRA": "PATO BRANCO",
                "SANTA IZABEL DO OESTE": "PATO BRANCO",
                "SANTO ANTONIO DO SUDOESTE": "PATO BRANCO",
                "SAO JOAO": "PATO BRANCO",
                "SAO JORGE DO OESTE": "PATO BRANCO",
                "SAUDADE DO IGUACU": "PATO BRANCO",
                "SULINA": "PATO BRANCO",
                "VERE": "PATO BRANCO",
                "VITORINO": "PATO BRANCO",
                "ARAPOTI": "PONTA GROSSA",
                "CANDIDO DE ABREU": "PONTA GROSSA",
                "CARAMBEI": "PONTA GROSSA",
                "CASTRO": "PONTA GROSSA",
                "FERNANDES PINHEIRO": "PONTA GROSSA",
                "GUAMIRANGA": "PONTA GROSSA",
                "IMBAU": "PONTA GROSSA",
                "IMBITUVA": "PONTA GROSSA",
                "INACIO MARTINS": "GUARAPUAVA",
                "IPIRANGA": "PONTA GROSSA",
                "IRATI": "PONTA GROSSA",
                "IVAI": "PONTA GROSSA",
                "JAGUARIAIVA": "PONTA GROSSA",
                "ORTIGUEIRA": "PONTA GROSSA",
                "PALMEIRA": "PONTA GROSSA",
                "PIRAI DO SUL": "PONTA GROSSA",
                "PONTA GROSSA": "PONTA GROSSA",
                "PORTO AMAZONAS": "PONTA GROSSA",
                "RESERVA": "PONTA GROSSA",
                "SENGES": "PONTA GROSSA",
                "TEIXEIRA SOARES": "PONTA GROSSA",
                "TELEMACO BORBA": "PONTA GROSSA",
                "TIBAGI": "PONTA GROSSA",
                "VENTANIA": "PONTA GROSSA",
                "ABATIA": "SANTO ANTONIO DA PLATINA",
                "ANDIRA": "SANTO ANTONIO DA PLATINA",
                "BANDEIRANTES": "SANTO ANTONIO DA PLATINA",
                "BARRA DO JACARE": "SANTO ANTONIO DA PLATINA",
                "CAMBARA": "SANTO ANTONIO DA PLATINA",
                "CARLOPOLIS": "SANTO ANTONIO DA PLATINA",
                "CONGONHINHAS": "SANTO ANTONIO DA PLATINA",
                "CONSELHEIRO MAIRINCK": "SANTO ANTONIO DA PLATINA",
                "CURIUVA": "SANTO ANTONIO DA PLATINA",
                "FIGUEIRA": "SANTO ANTONIO DA PLATINA",
                "GUAPIRAMA": "SANTO ANTONIO DA PLATINA",
                "IBAITI": "SANTO ANTONIO DA PLATINA",
                "ITAMBARACA": "SANTO ANTONIO DA PLATINA",
                "JABOTI": "SANTO ANTONIO DA PLATINA",
                "JACAREZINHO": "SANTO ANTONIO DA PLATINA",
                "JAPIRA": "SANTO ANTONIO DA PLATINA",
                "JOAQUIM TAVORA": "SANTO ANTONIO DA PLATINA",
                "JUNDIAI DO SUL": "SANTO ANTONIO DA PLATINA",
                "NOVA FATIMA": "SANTO ANTONIO DA PLATINA",
                "PINHALAO": "SANTO ANTONIO DA PLATINA",
                "QUATIGUA": "SANTO ANTONIO DA PLATINA",
                "RIBEIRAO CLARO": "SANTO ANTONIO DA PLATINA",
                "RIBEIRAO DO PINHAL": "SANTO ANTONIO DA PLATINA",
                "SALTO DO ITARARE": "SANTO ANTONIO DA PLATINA",
                "SANTA AMELIA": "SANTO ANTONIO DA PLATINA",
                "SANTA MARIANA": "SANTO ANTONIO DA PLATINA",
                "SANTANA DO ITARARE": "SANTO ANTONIO DA PLATINA",
                "SANTO ANTONIO DA PLATINA": "SANTO ANTONIO DA PLATINA",
                "SAO JOSE DA BOA VISTA": "SANTO ANTONIO DA PLATINA",
                "SIQUEIRA CAMPOS": "SANTO ANTONIO DA PLATINA",
                "TOMAZINA": "SANTO ANTONIO DA PLATINA",
                "WENCESLAU BRAZ": "SANTO ANTONIO DA PLATINA",
                "ALTO PARAISO": "UMUARAMA",
                "ALTO PIQUIRI": "UMUARAMA",
                "ALTONIA": "UMUARAMA",
                "BRASILANDIA DO SUL": "UMUARAMA",
                "CAFEZAL DO SUL": "UMUARAMA",
                "CIDADE GAUCHA": "UMUARAMA",
                "CRUZEIRO DO OESTE": "UMUARAMA",
                "DOURADINA": "UMUARAMA",
                "ESPERANCA NOVA": "UMUARAMA",
                "FRANCISCO ALVES": "UMUARAMA",
                "ICARAIMA": "UMUARAMA",
                "IPORA": "UMUARAMA",
                "IVATE": "UMUARAMA",
                "MARIA HELENA": "UMUARAMA",
                "MARILUZ": "UMUARAMA",
                "NOVA OLIMPIA": "UMUARAMA",
                "PEROBAL": "UMUARAMA",
                "PEROLA": "UMUARAMA",
                "QUERENCIA DO NORTE": "UMUARAMA",
                "SANTA MONICA": "UMUARAMA",
                "SAO JORGE DO PATROCINIO": "UMUARAMA",
                "TAPEJARA": "UMUARAMA",
                "TAPIRA": "UMUARAMA",
                "UMUARAMA": "UMUARAMA",
                "XAMBRE": "UMUARAMA",
                "ANTONIO OLINTO": "UNIÃO DA VITÓRIA",
                "BITURUNA": "UNIÃO DA VITÓRIA",
                "CRUZ MACHADO": "UNIÃO DA VITÓRIA",
                "GENERAL CARNEIRO": "UNIÃO DA VITÓRIA",
                "MALLET": "UNIÃO DA VITÓRIA",
                "PAULA FREITAS": "UNIÃO DA VITÓRIA",
                "PAULO FRONTIN": "UNIÃO DA VITÓRIA",
                "PORTO VITORIA": "UNIÃO DA VITÓRIA",
                "REBOUCAS": "UNIÃO DA VITÓRIA",
                "RIO AZUL": "UNIÃO DA VITÓRIA",
                "SAO JOAO DO TRIUNFO": "UNIÃO DA VITÓRIA",
                "SAO MATEUS DO SUL": "UNIÃO DA VITÓRIA",
                "UNIAO DA VITORIA": "UNIÃO DA VITÓRIA"
            ]

            let nomesMunicipios = [
                "ALTAMIRA DO PARANA",
                "ARARUNA",
                "BARBOSA FERRAZ",
                "BOA ESPERANCA",
                "CAMPINA DA LAGOA",
                "CAMPO MOURAO",
                "CORUMBATAI DO SUL",
                "ENGENHEIRO BELTRAO",
                "FAROL",
                "FENIX",
                "GOIOERE",
                "IRETAMA",
                "JANIOPOLIS",
                "JURANDA",
                "LUIZIANA",
                "MAMBORE",
                "MOREIRA SALES",
                "NOVA CANTU",
                "NOVA TEBAS",
                "PEABIRU",
                "QUARTO CENTENARIO",
                "QUINTA DO SOL",
                "RANCHO ALEGRE DO OESTE",
                "RONCADOR",
                "TERRA BOA",
                "TUNEIRAS DO OESTE",
                "UBIRATA",
                "ANAHY",
                "ASSIS CHATEAUBRIAND",
                "BOA VISTA DA APARECIDA",
                "BRAGANEY",
                "CAFELANDIA",
                "CAMPO BONITO",
                "CAPITAO LEONIDAS MARQUES",
                "CASCAVEL",
                "CATANDUVAS",
                "CEU AZUL",
                "CORBELIA",
                "DIAMANTE DO OESTE",
                "DIAMANTE DO SUL",
                "ENTRE RIOS DO OESTE",
                "ESPIGAO ALTO DO IGUACU",
                "FORMOSA DO OESTE",
                "FOZ DO IGUACU",
                "GUAIRA",
                "GUARANIACU",
                "IBEMA",
                "IGUATU",
                "IRACEMA DO OESTE",
                "ITAIPULANDIA",
                "JESUITAS",
                "LINDOESTE",
                "MARECHAL CANDIDO RONDON",
                "MARIPA",
                "MATELANDIA",
                "MEDIANEIRA",
                "MERCEDES",
                "MISSAL",
                "NOVA AURORA",
                "NOVA SANTA ROSA",
                "OURO VERDE DO OESTE",
                "PALOTINA",
                "PATO BRAGADO",
                "QUATRO PONTES",
                "QUEDAS DO IGUACU",
                "RAMILANDIA",
                "SANTA HELENA",
                "SANTA LUCIA",
                "SANTA TEREZA DO OESTE",
                "SANTA TEREZINHA DE ITAIPU",
                "SAO JOSE DAS PALMEIRAS",
                "SAO MIGUEL DO IGUACU",
                "SAO PEDRO DO IGUACU",
                "SERRANOPOLIS DO IGUACU",
                "TERRA ROXA",
                "TOLEDO",
                "TRES BARRAS DO PARANA",
                "TUPASSI",
                "VERA CRUZ DO OESTE",
                "ADRIANOPOLIS",
                "AGUDOS DO SUL",
                "ALMIRANTE TAMANDARE",
                "ANTONINA",
                "ARAUCARIA",
                "BALSA NOVA",
                "BOCAIUVA DO SUL",
                "CAMPINA GRANDE DO SUL",
                "CAMPO DO TENENTE",
                "CAMPO LARGO",
                "CAMPO MAGRO",
                "CERRO AZUL",
                "COLOMBO",
                "CONTENDA",
                "CURITIBA",
                "DOUTOR ULYSSES",
                "FAZENDA RIO GRANDE",
                "GUARAQUECABA",
                "GUARATUBA",
                "ITAPERUCU",
                "LAPA",
                "MANDIRITUBA",
                "MATINHOS",
                "MORRETES",
                "PARANAGUA",
                "PIEN",
                "PINHAIS",
                "PIRAQUARA",
                "PONTAL DO PARANA",
                "QUATRO BARRAS",
                "QUITANDINHA",
                "RIO BRANCO DO SUL",
                "RIO NEGRO",
                "SAO JOSE DOS PINHAIS",
                "TIJUCAS DO SUL",
                "TUNAS DO PARANA",
                "BOA VENTURA DE SAO ROQUE",
                "CAMPINA DO SIMAO",
                "CANDOI",
                "CANTAGALO",
                "FOZ DO JORDAO",
                "GOIOXIM",
                "GUARAPUAVA",
                "LARANJAL",
                "LARANJEIRAS DO SUL",
                "MARQUINHO",
                "MATO RICO",
                "NOVA LARANJEIRAS",
                "PALMITAL",
                "PINHAO",
                "PITANGA",
                "PORTO BARREIRO",
                "PRUDENTOPOLIS",
                "RESERVA DO IGUACU",
                "RIO BONITO DO IGUACU",
                "SANTA MARIA DO OESTE",
                "TURVO",
                "VIRMOND",
                "ALVORADA DO SUL",
                "APUCARANA",
                "ARAPONGAS",
                "ARAPUA",
                "ARIRANHA DO IVAI",
                "ASSAI",
                "BELA VISTA DO PARAISO",
                "BOM SUCESSO",
                "BORRAZOPOLIS",
                "CALIFORNIA",
                "CAMBE",
                "CAMBIRA",
                "CENTENARIO DO SUL",
                "CORNELIO PROCOPIO",
                "CRUZMALTINA",
                "FAXINAL",
                "FLORESTOPOLIS",
                "GODOY MOREIRA",
                "GRANDES RIOS",
                "IBIPORA",
                "IVAIPORA",
                "JAGUAPITA",
                "JANDAIA DO SUL",
                "JARDIM ALEGRE",
                "JATAIZINHO",
                "KALORE",
                "LEOPOLIS",
                "LIDIANOPOLIS",
                "LONDRINA",
                "LUNARDELLI",
                "MANOEL RIBAS",
                "MARILANDIA DO SUL",
                "MARUMBI",
                "MAUA DA SERRA",
                "MIRASELVA",
                "NOVA AMERICA DA COLINA",
                "NOVA SANTA BARBARA",
                "NOVO ITACOLOMI",
                "PITANGUEIRAS",
                "PORECATU",
                "PRADO FERREIRA",
                "PRIMEIRO DE MAIO",
                "RANCHO ALEGRE",
                "RIO BOM",
                "RIO BRANCO DO IVAI",
                "ROLANDIA",
                "ROSARIO DO IVAI",
                "SABAUDIA",
                "SANTA CECILIA DO PAVAO",
                "SANTO ANTONIO DO PARAISO",
                "SAO JERONIMO DA SERRA",
                "SAO JOAO DO IVAI",
                "SAO PEDRO DO IVAI",
                "SAO SEBASTIAO DA AMOREIRA",
                "SAPOPEMA",
                "SERTANEJA",
                "SERTANOPOLIS",
                "TAMARANA",
                "URAI",
                "ALTO PARANA",
                "AMAPORA",
                "ANGULO",
                "ASTORGA",
                "ATALAIA",
                "CAFEARA",
                "CIANORTE",
                "COLORADO",
                "CRUZEIRO DO SUL",
                "DIAMANTE DO NORTE",
                "DOUTOR CAMARGO",
                "FLORAI",
                "FLORESTA",
                "FLORIDA",
                "GUAIRACA",
                "GUAPOREMA",
                "GUARACI",
                "IGUARACU",
                "INAJA",
                "INDIANOPOLIS",
                "ITAGUAJE",
                "ITAMBE",
                "ITAUNA DO SUL",
                "IVATUBA",
                "JAPURA",
                "JARDIM OLINDA",
                "JUSSARA",
                "LOANDA",
                "LOBATO",
                "LUPIONOPOLIS",
                "MANDAGUACU",
                "MANDAGUARI",
                "MARIALVA",
                "MARILENA",
                "MARINGA",
                "MIRADOR",
                "MUNHOZ DE MELLO",
                "NOSSA SENHORA DAS GRACAS",
                "NOVA ALIANCA DO IVAI",
                "NOVA ESPERANCA",
                "NOVA LONDRINA",
                "OURIZONA",
                "PAICANDU",
                "PARAISO DO NORTE",
                "PARANACITY",
                "PARANAPOEMA",
                "PARANAVAI",
                "PLANALTINA DO PARANA",
                "PORTO RICO",
                "PRESIDENTE CASTELO BRANCO",
                "RONDON",
                "SANTA CRUZ DO MONTE CASTELO",
                "SANTA FE",
                "SANTA INES",
                "SANTA ISABEL DO IVAI",
                "SANTO ANTONIO DO CAIUA",
                "SANTO INACIO",
                "SAO CARLOS DO IVAI",
                "SAO JOAO DO CAIUA",
                "SAO JORGE DO IVAI",
                "SAO MANOEL DO PARANA",
                "SAO PEDRO DO PARANA",
                "SAO TOME",
                "SARANDI",
                "TAMBOARA",
                "TERRA RICA",
                "UNIFLOR",
                "AMPERE",
                "BARRACAO",
                "BELA VISTA DA CAROBA",
                "BOA ESPERANCA DO IGUACU",
                "BOM JESUS DO SUL",
                "BOM SUCESSO DO SUL",
                "CAPANEMA",
                "CHOPINZINHO",
                "CLEVELANDIA",
                "CORONEL DOMINGOS SOARES",
                "CORONEL VIVIDA",
                "CRUZEIRO DO IGUACU",
                "DOIS VIZINHOS",
                "ENEAS MARQUES",
                "FLOR DA SERRA DO SUL",
                "FRANCISCO BELTRAO",
                "HONORIO SERPA",
                "ITAPEJARA DO OESTE",
                "MANFRINOPOLIS",
                "MANGUEIRINHA",
                "MARIOPOLIS",
                "MARMELEIRO",
                "NOVA ESPERANCA DO SUDOESTE",
                "NOVA PRATA DO IGUACU",
                "PALMAS",
                "PATO BRANCO",
                "PEROLA DO OESTE",
                "PINHAL DE SAO BENTO",
                "PLANALTO",
                "PRANCHITA",
                "REALEZA",
                "RENASCENCA",
                "SALGADO FILHO",
                "SALTO DO LONTRA",
                "SANTA IZABEL DO OESTE",
                "SANTO ANTONIO DO SUDOESTE",
                "SAO JOAO",
                "SAO JORGE DO OESTE",
                "SAUDADE DO IGUACU",
                "SULINA",
                "VERE",
                "VITORINO",
                "ARAPOTI",
                "CANDIDO DE ABREU",
                "CARAMBEI",
                "CASTRO",
                "FERNANDES PINHEIRO",
                "GUAMIRANGA",
                "IMBAU",
                "IMBITUVA",
                "INACIO MARTINS",
                "IPIRANGA",
                "IRATI",
                "IVAI",
                "JAGUARIAIVA",
                "ORTIGUEIRA",
                "PALMEIRA",
                "PIRAI DO SUL",
                "PONTA GROSSA",
                "PORTO AMAZONAS",
                "RESERVA",
                "SENGES",
                "TEIXEIRA SOARES",
                "TELEMACO BORBA",
                "TIBAGI",
                "VENTANIA",
                "ABATIA",
                "ANDIRA",
                "BANDEIRANTES",
                "BARRA DO JACARE",
                "CAMBARA",
                "CARLOPOLIS",
                "CONGONHINHAS",
                "CONSELHEIRO MAIRINCK",
                "CURIUVA",
                "FIGUEIRA",
                "GUAPIRAMA",
                "IBAITI",
                "ITAMBARACA",
                "JABOTI",
                "JACAREZINHO",
                "JAPIRA",
                "JOAQUIM TAVORA",
                "JUNDIAI DO SUL",
                "NOVA FATIMA",
                "PINHALAO",
                "QUATIGUA",
                "RIBEIRAO CLARO",
                "RIBEIRAO DO PINHAL",
                "SALTO DO ITARARE",
                "SANTA AMELIA",
                "SANTA MARIANA",
                "SANTANA DO ITARARE",
                "SANTO ANTONIO DA PLATINA",
                "SAO JOSE DA BOA VISTA",
                "SIQUEIRA CAMPOS",
                "TOMAZINA",
                "WENCESLAU BRAZ",
                "ALTO PARAISO",
                "ALTO PIQUIRI",
                "ALTONIA",
                "BRASILANDIA DO SUL",
                "CAFEZAL DO SUL",
                "CIDADE GAUCHA",
                "CRUZEIRO DO OESTE",
                "DOURADINA",
                "ESPERANCA NOVA",
                "FRANCISCO ALVES",
                "ICARAIMA",
                "IPORA",
                "IVATE",
                "MARIA HELENA",
                "MARILUZ",
                "NOVA OLIMPIA",
                "PEROBAL",
                "PEROLA",
                "QUERENCIA DO NORTE",
                "SANTA MONICA",
                "SAO JORGE DO PATROCINIO",
                "TAPEJARA",
                "TAPIRA",
                "UMUARAMA",
                "XAMBRE",
                "ANTONIO OLINTO",
                "BITURUNA",
                "CRUZ MACHADO",
                "GENERAL CARNEIRO",
                "MALLET",
                "PAULA FREITAS",
                "PAULO FRONTIN",
                "PORTO VITORIA",
                "REBOUCAS",
                "RIO AZUL",
                "SAO JOAO DO TRIUNFO",
                "SAO MATEUS DO SUL",
                "UNIAO DA VITORIA"
            ]

            for nome in nomesMunicipios {
                // Normalize for lookup
                let chaveNormalizada = nome
                    .uppercased()
                    .folding(options: .diacriticInsensitive, locale: .current)

                // Try to find existing municipio by name (case/diacritic insensitive)
                let fetch: NSFetchRequest<Municipio> = Municipio.fetchRequest()
                fetch.fetchLimit = 1
                fetch.predicate = NSPredicate(format: "(nome LIKE[cd] %@)", nome)

                let existente = try? viewContext.fetch(fetch).first
                let municipio = existente ?? Municipio(context: viewContext)

                // Populate fields
                municipio.nome = nome
                municipio.regional = mapaRegionais[chaveNormalizada] ?? "Não definida"

                // If your Core Data model has these optional attributes, set them here safely
                if municipio.responds(to: Selector(("setFavorito:"))) && municipio.value(forKey: "favorito") == nil {
                    municipio.setValue(false, forKey: "favorito")
                }
                if municipio.responds(to: Selector(("setId:"))) && municipio.value(forKey: "id") == nil {
                    municipio.setValue(UUID(), forKey: "id")
                }
                if municipio.responds(to: Selector(("setCreatedAt:"))) && municipio.value(forKey: "createdAt") == nil {
                    municipio.setValue(Date(), forKey: "createdAt")
                }
                if municipio.responds(to: Selector(("setUpdatedAt:"))) {
                    municipio.setValue(Date(), forKey: "updatedAt")
                }
            }

            try viewContext.save()
            fetchMunicipios()

        } catch {
            print("Erro ao popular municípios: \(error)")
        }
    }
}

